const wordList = [
    { word: "cat", hint: "a small pet animal" },
    { word: "sun", hint: "gives us light and heat" },
    { word: "pen", hint: "used for writing" },
    { word: "apple", hint: "a red fruit" },
    { word: "car", hint: "used for travelling" },
    { word: "book", hint: "used for reading" },
    { word: "fish", hint: "lives in water" },
    { word: "milk", hint: "a white drink" },
    { word: "ball", hint: "used in many games" },
    { word: "tree", hint: "gives shade and oxygen" },
    { word: "bird", hint: "can fly in the sky" },
    { word: "shoe", hint: "wear on your feet" },
    { word: "cake", hint: "sweet dessert" },
    { word: "door", hint: "used to enter or exit" },
    { word: "star", hint: "shines in the night sky" },
    { word: "moon", hint: "seen at night" },
    { word: "cup", hint: "used to drink tea or coffee" },
    { word: "egg", hint: "comes from a hen" },
    { word: "dog", hint: "a loyal pet animal" },
    {word: "html",hint: "markup language for the web"},
    {word: "mysql",hint: "a relational database system"},
    {word: "dubai",hint: "developed country name"},
    {word: "rain",hint: "related to a water"},
    {word: "guitar",hint: "a musical instrument"},
];
